protected/controllers/CarsController.php
<?php

class CarsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','admin','delete','create','update'),
                'roles'=>array(Admin::STATUS_MANAGER),
            ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		Meta::make($this, 'Просмотр автомобиля');

		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		Meta::make($this, 'Создание автомобиля');

		$model=new Car;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Car']))
		{
			$model->attributes=$_POST['Car'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		Meta::make($this, 'Редактирование автомобиля');

		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Car']))
		{
			$model->attributes=$_POST['Car'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		Meta::make($this, 'Удаление автомобиля');

		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $this->redirect(Yii::app()->createAbsoluteUrl(Yii::app()->controller->id.'/admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		Meta::make($this, 'Просмотр списка автомобилей');

		$model=new Car('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Car']))
			$model->attributes=$_GET['Car'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Car the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Car::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Car $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='car-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/CityController.php
<?php

class CityController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','admin','delete','create','update'),
				'roles'=>array(Admin::STATUS_MANAGER),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		Meta::make($this, 'Просмотр города');

		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		Meta::make($this, 'Создание города');

		$model=new City;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['City']))
		{
			$model->attributes=$_POST['City'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		Meta::make($this, 'Редактирование города');

		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['City']))
		{
			$model->attributes=$_POST['City'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		Meta::make($this, 'Удаление города');

		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $this->redirect(Yii::app()->createAbsoluteUrl(Yii::app()->controller->id.'/admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		Meta::make($this, 'Просмотр списка городов');

		$model=new City('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['City']))
			$model->attributes=$_GET['City'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return City the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=City::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param City $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='city-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	//просмотр всех товаров $opp количество товаров на странице, в идеале кратное 3
	public function actionIndex($opp = 12)
	{
		Meta::make($this);

		$this->render('search');
//		$criteria = Goods::model()->with('category')->getDbCriteria();
//		$pages = new CPagination(Goods::model()->count($criteria));
//		$pages->pageSize = $opp;
//		$pages->applyLimit($criteria);
//		$goods = Goods::model()->findAll($criteria);
//		$this->render('index', array('goods' => $goods, 'pages' => $pages));
	}

    public function actionCatalog($opp = 12)
    {

		Meta::make($this, 'Каталог товаров');

		$criteria = Goods::model()->with('category')->getDbCriteria();
		$pages = new CPagination(Goods::model()->count($criteria));
		$pages->pageSize = $opp;
		$pages->applyLimit($criteria);
		$goods = Goods::model()->findAll($criteria);
		$this->render('index', array('goods' => $goods, 'pages' => $pages));
    }

	//просмотр товара
	public function actionView($id)
	{
		//
		$item = Goods::model()->with('category')->findByPk($id);
		if ($item) {
			Meta::make($this, $item->name, $item->kw, $item->ds);
			$this->render('view', array('item' => $item));
		} else {
			Meta::make($this, 'Просмотреть товар');
			$this->render('view', array('error' => 'Not Found'));

		}
	}

	//добавить элемент в корзину
	public function actionPut($id)
	{
		Yii::app()->ShoppingCart->put($id);
		Yii::app()->user->setFlash('success','Товар успешно добавлен в корзину');
		$this->redirect(Yii::app()->createAbsoluteUrl('site/catalog'));
	}

	//удалить элемент из корзины
	public function actionUnsete($id)
	{
		Yii::app()->ShoppingCart->remove($id);
		Yii::app()->user->setFlash('success','Товар успешно удален из корзины');

		$this->redirect(Yii::app()->createAbsoluteUrl('site/catalog'));
	}

	//очистить корзину
	public function actionClear($status = 'nothing')
	{
		Yii::app()->ShoppingCart->clear();
		//die($status);
		if($status=='kop'){
			Yii::app()->user->setFlash('info','Заказ оформлен');
		}
		Yii::app()->user->setFlash('success','Корзина очищена');
		$this->redirect(Yii::app()->createAbsoluteUrl('site/catalog'));


	}

	//сделать заказ
	public function actionCheckout()
	{
		Meta::make($this, 'Оформить заказ');

		$order = new Orders();
		if(Yii::app()->request->getPost('Orders')){
			$order->attributes = Yii::app()->request->getPost('Orders');
			$order->payment = 'Наличные';
			if($order->save()){
				$this->redirect(Yii::app()->createAbsoluteUrl('site/clear?status=kop'));
			}
		}
		$this->render('checkout',array('model'=>$order));
	}
	/**
	 * This is the action to handle external exceptions.
	 */
	//сообщение об ошибке
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (!Yii::app()->request->isAjaxRequest)
				$this->render('error', $error);
		}
	}

	//Логин
	public function actionLogin()
	{
		Meta::make($this, 'Авторизация');

		if (!Yii::app()->user->isGuest) {
			$this->redirect(Yii::app()->user->returnUrl);
		}
		$model = new Admin('login');

		if ($model->attributes = Yii::app()->request->getPost('Admin')) {

			if ($model->login()) {
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		$this->render('login', array('model' => $model));
	}


	//вывод списка категорий
	public function actionCategories()
	{
		$categories = Category::model()->findAll();
		$this->render('category', array('items' => $categories));
	}

	//вывод по категориям
	public function actionBy($id)
	{
		/** @var Category $cat */
		$cat = Category::model()->findByPk($id);
		Meta::make($this, 'Все товары из'.$cat->name);

		$criteria = Goods::model()->with('category')->byCategory($id)->getDbCriteria();
		$pages = new CPagination(Goods::model()->count($criteria));
		$pages->pageSize = 12;
		$pages->applyLimit($criteria);
		$goods = Goods::model()->findAll($criteria);
		$this->render('index', array('goods' => $goods, 'pages' => $pages));
	}

	//обратная связь
	public function actionBack()
	{
		if (Yii::app()->request->getPost('Mail')) {
			$from = Yii::app()->request->getPost('Mail');

			$message = "Message sent!";
			$mail = Yii::app()->mailer;
			$mail->SetFrom(Yii::app()->params['techemail'], Yii::app()->params['project']);
			$mail->AddAddress(Yii::app()->params['shopEmail'], Yii::app()->params['adminName']);
			$mail->IsHTML(true); // set email format to HTML
			$mail->Subject = "С сайта " . Yii::app()->params['project'];
			$mail->Body = 'Сообщение от ' . $from['name'] . '(' . $from['email'] . ')<br/>' .
				(($from['tel']) ? 'Тел: ' . $from['tel'] . '<br/>' : '') .
				$from['message'];
			$mail->AltBody = 'Сообщение от ' . $from['name'] . '(' . $from['email'] . ')\n' .
				(($from['tel']) ? 'Тел: ' . $from['tel'] . '\n' : '') .
				$from['message'];
			if (!$mail->Send()) {
				$this->render('back', array('status' => 'fail'));
			} else {
				$this->render('back', array('status' => 'success'));
			}
		}
		$this->render('back');
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	//выход
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}


	public function actionSearch($kw, $limit = 20, $offset = 0,$new = -1,$page = 0)
	{

		$this->renderPartial('search',array('kw'=>$kw));
		if(strlen($kw)<=3){
			return false;
		}
		$goods = Goods::model();
		$cat = Category::model()->findByAttributes(array('name' => $kw));
		$wh = Warehouse::model()->findByAttributes(array('description' => $kw));
		$criteria = new CDbCriteria;
		$criteria->compare('id', $kw, 'OR');
		$criteria->compare('code', $kw, true, 'OR');
		$criteria->compare('category_id', $kw, true, 'OR');
		$criteria->compare('category_id', $kw, true, 'OR');
		$criteria->compare('name', $kw, true, 'OR');
		if ($cat)
			$criteria->compare('path', $cat->id, true, 'OR');

		$criteria->compare('description', $kw, true, 'OR');
		$criteria->compare('pricex100', $kw, true, 'OR');
		if ($wh)
			$criteria->compare('warehouse_id', $wh->id, true, 'OR');

		$criteria->compare('warehouse_id', $kw, true, 'OR');

		if($new == -1){
		$count = Goods::model()->count($criteria);
		}else{
			$count = $new;
		}
		$criteria->limit = $limit;
		$criteria->offset = $page*$limit;
		$res = Goods::model()->findAll($criteria);

		echo '<div class="btn-group">';
		for($i=0;$i<intval($count/$limit);$i++){
			$active = '';
			if($i == $page){
				$active = 'active';
			}
			echo ((intval($count/$limit))>1)?"<span class='btn btn-success spager $active' data-offset='$offset'
			data-kw='$kw'
			data-count='$count' data-limi='$limit'
		 data-page='$i'>".($i+1)."</span>":($count/$limit);
		}
		echo '</div><hr/>';

		foreach ($res as $item) {
			echo $this->makeDiv($item);
		}

	}

	protected function makeDiv($item)
	{
		$div = '';
		$div .= '<div class="col-sm-3 goods_item">';

		$div .= '<h2>#' . $item->id . ' ' . $item->name . '</h2>';
		$div .= '<sup>' . $item->code . '</sup><br/>';
		$div .= $item->getImage();
		$div .= '<p>';
		if (strlen($item->description) >= 200) {
			$div .= substr($item->description, 0, 200) . '...';
		} else {
			$div .= $item->description;
		}
		$div .= '</p>';
		$div .= '<p>' . $item->getPriceLabel() . '</p>';
		$div .= '<p>' . $item->getStatus() . '</p>';
		$div .= '<p><a class="btn btn-default" href="' . Yii::app()->createAbsoluteUrl('site/view/' . $item->id) . '"
	  role="button">Подробней»</a>';

		if ($item->status != 0)
			$div .= '<a class="btn btn-success" href="' . Yii::app()->createAbsoluteUrl('site/put/' . $item->id) . '"
		   role="button">Заказать</a>';
		$div .= '</p>
</div>';
		return $div;
	}
}

protected/views/layouts/_menu.php
<?php

function makeStatusDiv(){
	$res = '';

	if(Yii::app()->user->role_id){

		if(Yii::app()->user->role_id<=1){
			$res = '<span class="label-warning label text-left pull-left" style="border-radius: 0 0 3px 3px;padding-top: 15px">Manager</span>';
		}

		if(Yii::app()->user->role_id==2){
			$res = '<span class="label-danger label text-left pull-left" style="border-radius: 0 0 3px 3px;padding-top: 15px">Admin</span>';
		}
	}
	echo $res;
}

function getItems()
{
	$user = Yii::app()->user;
	return array(
		array('label'=>Yii::app()->params['project'], 'url'=>Yii::app()->createAbsoluteUrl('/'),
			'visible'=>$user->isGuest),
		array('label' => 'Главная', 'url' => Yii::app()->createAbsoluteUrl('/site/index')),
		array('label' => 'Каталог', 'url' => Yii::app()->createAbsoluteUrl('/site/catalog')),
//		array('label' => 'Категории', 'url' => Yii::app()->createAbsoluteUrl('/site/categories')),
		array('label' => 'Обратная связь', 'url' => Yii::app()->createAbsoluteUrl('/site/back'),
			'visible' => $user->isGuest),
		array('label'=>'Отследить заказ','url'=>array('/orders/check')),
		array('label' => 'Выход ||' ,'url' => array('/site/logout'), 'visible' => !$user->isGuest),
		array('label' => 'Вход', 'url' => array('/site/login'), 'visible' => $user->isGuest),
		array('label'=>'Товары','url'=>array('/goods/index'),'visible'=> $user->checkAccess(Admin::STATUS_MANAGER)),

		array('label'=>'Добавить товар', 'url'=>array('create'),'visible'=>(Yii::app()
					->controller->id=="goods"&&Yii::app()
					->controller->action->id=='index')?true:false),
		array('label'=>'Быстрый просмотр товаров', 'url'=>array('admin'),'visible'=>(Yii::app()
					->controller->id=="goods"&&Yii::app()->controller->action->id=='index')?true:false),

		array('label'=>'Быстрый просмотр товаров', 'url'=>array('admin'),'visible'=>(Yii::app()
					->controller->id=="goods"&&Yii::app()->controller->action->id=='create')?true:false),

		array('label'=>'Добавить товар', 'url'=>array('create'),'visible'=>(Yii::app()
					->controller->id=="goods"&&Yii::app()
					->controller->action->id=='admin')?true:false),

		array('label'=>'Добавить товар', 'url'=>array('create'),'visible'=>(Yii::app()
					->controller->id=="goods"&&Yii::app()
					->controller->action->id=='update')?true:false),
		array('label'=>'Быстрый просмотр товаров', 'url'=>array('admin'),'visible'=>(Yii::app()
					->controller->id=="goods"&&Yii::app()->controller->action->id=='update')?true:false),



		array('label'=>'Клиенты','url'=>array('/client/index'),'visible'=> $user->checkAccess(Admin::STATUS_MANAGER)),


//		array('label'=>'Города','url'=>array('/city/index'),'visible'=> $user->checkAccess
//				(Admin::STATUS_MANAGER)),



		array('label'=>'Склады','url'=>array('/warehouse/index'),'visible'=> $user->checkAccess
				(Admin::STATUS_MANAGER)),




//		array('label'=>'Автомобили','url'=>array('/cars/index'),'visible'=> $user->checkAccess(Admin::STATUS_MANAGER)),
		array('label'=>'Категории товаров','url'=>array('/category/index'),'visible'=> $user->checkAccess
				(Admin::STATUS_MANAGER)),

		array('label'=>'Сотрудники','url'=>array('/admin/index'),'visible'=> $user->checkAccess(Admin::STATUS_ADMIN)),
        array('label'=>'Списки заказов', 'url'=>array('orders/admin'),'visible'=>$user->checkAccess(Admin::STATUS_MANAGER)),
        array('label'=>'Проверка email', 'url'=>array('client/search'),'visible'=>$user->checkAccess(Admin::STATUS_MANAGER)),
	);
}


?>





<div class="navbar navbar-inverse" style=" margin-bottom:0px !important;border-radius: 0px;" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<?
			makeStatusDiv();
			$this->widget('zii.widgets.CMenu', array(
				'items' => getItems(),
				'htmlOptions' => array('class' => 'nav navbar-nav')
			));
			?>
		</div>
	</div>
</div>

protected/views/layouts/_rbar.php
<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 18.09.14
 * Time: 19:29
 */
?>
<? if(Yii::app()->controller->id=='site'){?>
<div class="col-xs-3 sidebar-offcanvas <?=(Yii::app()->controller->action->id=='index')?'hidden':''?>" id="sidebar"
role="navigation">
	<div class="list-group cart_bar">
		<p class="list-group-item list-group-item-info cart_hat"><span class="glyphicon glyphicon-shopping-cart"></span> Корзина </p>
		<?
		echo Yii::app()->ShoppingCart->makeCartList();
		?>
	</div>
        <div class="list-group cart_bar">
            <p class="list-group-item list-group-item-info cart_hat"><span class="glyphicon glyphicon-list"></span> Каталог </p>
            <?
//                    Category::model()->rebuildPaths();  // For rebuilding of comments paths
//            $model2 = Category::model()->orderHierarchy('DESC')->findAll();
//            foreach ($model2 as $category) {
//                ?>
<!--                <div class="col-xs-12" style="padding:4px; padding-left: 10px;">-->
<!--                    <div style="text-align:left;padding:0px;padding-left:--><?//=$category->getLevel() * 20?><!--px;">-->
<!-- --><?//="<a href='".Yii::app()->createAbsoluteUrl('site/by/'.$category->id)."'>".$category->name."</a>   ".$category->path?><!--</div>-->
<!--                </div>-->
<!--            --><?//
//            }

            $model3 = Category::model()->findAll();
            $menu=array();
            foreach($model3 as $category)
            {
                array_push($menu,array('id'=>$category->id,'name'=>$category->name, 'parent_id'=>$category->parent_id));
            }
            foreach($menu as $lol)
            {
                $data[$lol[id]] = $lol;
            }
            function view_cat ($dataset) {
                foreach ($dataset as $menu) {
                    echo '<li><a href="'.Yii::app()->createAbsoluteUrl('site/by/'.$menu['id']).'">'.$menu["name"].'</a>';
                    if($menu['childs']) {
                        echo '<ul>';
                        view_cat($menu['childs']);
                        echo '</ul>';
                    }
                    echo '</li>';
                }
            }
            function mapTree($dataset) {
                $tree = array();
                foreach ($dataset as $id=>&$node) {
                    if (!$node['parent_id']) {
                        $tree[$id] = &$node;
                    }
                    else {
                        $dataset[$node['parent_id']]['childs'][$id] = &$node;
                    }
                }
                return $tree;
            }
            // вызываем функцию и передаем ей наш массив
            $data = mapTree($data);

		echo "<div id='tree' class='text-left'>";
			echo '<ul>';
			view_cat($data);
			echo '</ul>';
		echo "</div>";

//            die(var_dump($menu));
//            foreach ($model2 as $category) {

//                function printTree($t,$lvl = 0){
//                    if($lvl == 0){
//                        echo "$lvl : $t->value <br/>";
//                    }
//                    $lvl+=1;
//                    if(count($t->subItems)>0){
//                        foreach($t->subItems as $k=>$v){
//                            echo $lvl." : ".$t->subItems[$k]->value."<br/>";
//                            printTree($t->subItems[$k],$lvl);
//                        }
//                    }
//                }



//                if(count(Yii::app()->findByAttributes(array('parent_id'=>$category->parent_id)))>0){
//                    foreach($t->subItems as $k=>$v){
//                        echo $t->subItems[$k]->value."<br/>";
//                        printTree($t->subItems[$k]);
//                    }
//                }
                    ?>

<!--                    <div style="text-align:left;padding:0px;padding-left:--><?//=$category->getLevel() * 20?><!--px;">-->
<!--                        --><?//=$category->getLevel().'__'. $category->name."____".$category->path?>
<!--                    </div>-->
            <?
//            }




            //(L'.$category->getLevel().') служит для получения уровня вложенности
//            echo Yii::app()->ShoppingCart->makeCartList();
            ?>
            <div class="cart_footer"></div>

        </div>
    </div><!--/span-->
<?}?>

protected/views/layouts/column1.php
<?php /* @var Controller $this */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var Controller $this */ ?>
<?php $this->beginContent('//layouts/main'); ?>


	<div class="col-xs-12">
		<div id="content">
			<?= $content; ?>
		</div>
		<!-- content -->
	</div>
	<div class="col-xs-2 text-left last" id="sidebarp">
		<div id="sidebar">
			<?php
			$this->widget('bootstrap.widgets.TbMenu', array(
				'items' => $this->menu,
				'htmlOptions' => array('class' => 'operations'),
			));
			?>
		</div>
		<!-- sidebar -->
	</div>
<?php $this->endContent(); ?>