protected/models/Client.php
<?php

/**
 * This is the model class for table "clients".
 *
 * The followings are the available columns in table 'clients':
 * @property integer $id
 * @property string $login
 * @property string $name
 * @property string $surname
 * @property string $father_name
 * @property string $tel
 * @property string $tel_coment
 * @property string $tel2
 * @property string $tel2_comment
 * @property string $tel3
 * @property string $tel3_comment
 * @property string $email
 * @property string $email2
 * @property string $password
 * @property integer $city_id
 * @property string $organization
 * @property integer $active
 *
 * The followings are the available model relations:
 * @property Cars[] $cars
 * @property Cities $city
 */
class Client extends CActiveRecord
{
	const STATUS_ACTIVE = 1;
	const STATUS_UNACTIVE = 0;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'clients';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('login, name', 'required'),
            array('email,email2', 'unique'),
			array('city_id, active', 'numerical', 'integerOnly'=>true),
			array('login, name, surname, father_name, tel, tel_coment, tel2, tel2_comment, tel3, tel3_comment,
			email, email2, password, organization', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, login, name, surname, father_name, tel, tel_coment, tel2, tel2_comment, tel3, tel3_comment,
			email, email2, password, city_id, organization, active', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'cars' => array(self::HAS_MANY, 'Cars', 'user_id'),
			'city' => array(self::BELONGS_TO, 'Cities', 'city_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'login' => 'Логин',
			'name' => 'Имя',
			'surname' => 'Фамилия',
			'father_name' => 'Отчество',
			'tel' => 'Телефон',
			'tel_coment' => 'Комментарий к телефону',
			'tel2' => 'Рабочий телефон',
			'tel2_comment' => 'Комментарий к рабочему телефону',
			'tel3' => 'Мобильный',
			'tel3_comment' => 'Комментарий к мобильному',
			'email' => 'Email',
			'email2' => 'Второй email',
			'password' => 'Пароль',
			'city_id' => 'Город',
			'organization' => 'Организация',
			'active' => 'Статус',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('login',$this->login,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('surname',$this->surname,true);
		$criteria->compare('father_name',$this->father_name,true);
		$criteria->compare('tel',$this->tel,true);
		$criteria->compare('tel_coment',$this->tel_coment,true);
		$criteria->compare('tel2',$this->tel2,true);
		$criteria->compare('tel2_comment',$this->tel2_comment,true);
		$criteria->compare('tel3',$this->tel3,true);
		$criteria->compare('tel3_comment',$this->tel3_comment,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('email2',$this->email2,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('city_id',$this->city_id);
		$criteria->compare('organization',$this->organization,true);
		$criteria->compare('active',$this->active);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	public function delete(){
		$this->active = self::STATUS_UNACTIVE;
		return $this->save();
	}

	public function activate(){
		$this->active = self::STATUS_ACTIVE;
		return $this->save();
	}

    public function sendMail($text,$email)
    {
        $message = "Message sent!";
        $mail = Yii::app()->mailer;
        $mail->AddAddress($email);
        $mail->IsHTML(true); // set email format to HTML
        $mail->Subject = "From some good man";
        $mail->Body = $text;
        if (!$mail->Send()) {
            $message = "Message could not be sent. <p>";
            $message = "Mailer Error: " . $mail->ErrorInfo;
            return false;
        }
        return true;
    }


    /**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Client the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ClientController.php
<?php

class ClientController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('admin','create','update','index','view','search'),
				'roles'=>array(Admin::STATUS_MANAGER),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete'),
				'roles'=>array(Admin::STATUS_ADMIN),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		Meta::make($this, 'Просмотреть данные клиента');

		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{

		Meta::make($this, 'Создать клиента');

		$model=new Client;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Client']))
		{
			$model->attributes=$_POST['Client'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

    public function actionSearch(){
		Meta::make($this, 'Новый клиента');

		$client = new Client('search');
        if(Yii::app()->request->getPost('Client'))
        {
            $client->attributes = Yii::app()->request->getPost('Client');
            if(Client::model()->findByAttributes(array('email'=>$client->email)))
            {
                $model = Client::model()->findByAttributes(array('email'=>$client->email));
                $this->redirect(Yii::app()->createAbsoluteUrl('/client/'.$model->id));
            }
            else{
            if(Client::model()->findByAttributes(array('email2'=>$client->email)))
            {
                $model = Client::model()->findByAttributes(array('email2'=>$client->email));
                $this->redirect(Yii::app()->createAbsoluteUrl('/client/'.$model->id));
            }
                else{
                    $answer = 'No such Email in the data base';
                    $this->render('search',array('model'=>$client,'answer'=>$answer));}
            }
        }
        else
        {
            $answer = '';
            $this->render('search',array('model'=>$client,'answer'=>$answer));
        }

    }

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		Meta::make($this, 'Редактировать клиента');

		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Client']))
		{
			$model->attributes=$_POST['Client'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		Meta::make($this, 'Удалить клиента');

		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	public function actionActivate($id)
	{
		Meta::make($this, 'Активировать клиента');

		$this->loadModel($id)->activate();
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
	$this->redirect(Yii::app()->createAbsoluteUrl('client/admin'));
	}

    public function actionSendPassword($id){
		Meta::make($this, 'Отправить пароль клиенту');

		$model = Client::model()->findByPk($id);
        $model->sendMail('Your password is '.$model->password,$model->email);
        $model->sendMail('Your password is '.$model->password,$model->email2);
        $this->redirect(Yii::app()->createAbsoluteUrl('client'));
    }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		Meta::make($this, 'Просмотр списка клиентов');

		$model=new Client('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Client']))
			$model->attributes=$_GET['Client'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Client the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Client::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Client $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='client-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/client/_form.php
<?php
/* @var $this ClientController */
/* @var $model Client */
/* @var $form CActiveForm */
?>


<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'client-form',
    'htmlOptions' => array('class' => 'form-horizontal','style'=>'padding-left:50px;'),
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'login', array('class'=>'input-group-addon alert-danger','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'login', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'login',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'name', array('class'=>'input-group-addon alert-danger','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'name', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'name',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'surname', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'surname', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'surname',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'father_name', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'father_name', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'father_name',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'tel', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'tel', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'tel',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'tel_coment', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'tel_coment', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'tel_coment',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'tel2', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'tel2', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'tel2',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'tel2_comment', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'tel2_comment', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'tel2_comment',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'tel3', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'tel3', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'tel3',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'tel3_comment', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'tel3_comment', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'tel3_comment',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'email', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'email', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'email',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'email2', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'email2', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'email2',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'password', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'password', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'password',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'city_id', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'city_id', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'city_id',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'organization', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?php echo $form->textField($model, 'organization', array('maxlength' => 255, 'class' => 'form-control','style' => 'height: 100%')); ?>
    </div>
    <?=$form->error($model, 'organization',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row" style="margin-bottom: 13px;">
    <div class="input-group col-xs-10">
        <?=$form->labelEx($model,'active', array('class'=>'input-group-addon alert-info','style'=>'width: 30%')); ?>
        <?=$form->dropDownList($model, 'active', array(Client::STATUS_ACTIVE => 'Активирован', Client::STATUS_UNACTIVE => 'Не активирован'), array('class' => 'form-control'));?>
    </div>
    <?=$form->error($model, 'active',array('class'=>"label label-danger col-xs-10")); ?>
</div>

<div class="row buttons">
    <?php echo CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить',array('class'=>'btn btn-success')); ?>
</div>
<?php $this->endWidget(); ?>

protected/views/client/_search.php
<?php
/* @var $this ClientController */
/* @var $model Client */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'login'); ?>
		<?php echo $form->textField($model,'login',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surname'); ?>
		<?php echo $form->textField($model,'surname',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'father_name'); ?>
		<?php echo $form->textField($model,'father_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tel'); ?>
		<?php echo $form->textField($model,'tel',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tel_coment'); ?>
		<?php echo $form->textField($model,'tel_coment',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tel2'); ?>
		<?php echo $form->textField($model,'tel2',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tel2_comment'); ?>
		<?php echo $form->textField($model,'tel2_comment',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tel3'); ?>
		<?php echo $form->textField($model,'tel3',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tel3_comment'); ?>
		<?php echo $form->textField($model,'tel3_comment',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email2'); ?>
		<?php echo $form->textField($model,'email2',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'city_id'); ?>
		<?php echo $form->textField($model,'city_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'organization'); ?>
		<?php echo $form->textField($model,'organization',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'active'); ?>
		<?php echo $form->textField($model,'active'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/client/admin.php
<?php
/* @var $this ClientController */
/* @var $model Client */

$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Manage',
);

$this->menu=array(
    array('label'=>'Создать клиента', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#client-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<div class="col-xs-12 block">
    <div class="col-xs-12 block_header">
<h1>Управление Клиентами</h1>
    </div>
    <div class="col-xs-12 block_inner">

<?php echo CHtml::link('Продвинутый поиск','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'client-grid',
    'type' => 'striped bordered condensed',
	'dataProvider'=>$model->search(),
    'summaryText'=>false,
//	'filter'=>$model,
	'columns'=>array(
		'id',
		'login',
		'name',
		'surname',
		'father_name',
		'tel',
		/*
		'tel_coment',
		'tel2',
		'tel2_comment',
		'tel3',
		'tel3_comment',
		'email',
		'email2',
		'password',
		'city_id',
		'organization',
		'active',
		*/
        array(
            'header' => 'Actions',
            'class' => 'CButtonColumn',
            'template' => '{update}{view}{pass}{delete}',
            'htmlOptions' => array('class'=>'btn-group col-xs-3'),
            'buttons' => array
            (
                'update' => array
                (
                    'imageUrl' => false,
                    'label' => '<span type="button" class="glyphicon glyphicon-pencil"></span>',
                    'options' => array('title' => 'Редактировать', 'class' => 'text-center btn btn-success '),
                    'url'=>'Yii::app()->createUrl("client/update/", array("id"=>$data->id))',
                    'click'=>'',
                ),

                'view' => array
                (
                    'imageUrl' => false,
                    'label' => '<span type="button" class=" glyphicon glyphicon-eye-open"></span>',
                    'options' => array('title' => 'Просмотр', 'class' => 'text-center btn btn-info'),
                    'url'=>'Yii::app()->createUrl("client/view", array("id"=>$data->id))',
                    'click'=>'',
                ),
                'pass' => array
                (
                    'imageUrl' => false,
                    'label' => '<span type="button" class=" glyphicon glyphicon-envelope"></span>',
                    'options' => array('title' => 'Востановить пароль', 'class' => 'text-center btn btn-warning'),
                    'url'=>'Yii::app()->createUrl("client/sendpassword", array("id"=>$data->id))',

                ),
                'delete' => array
                (
                    'imageUrl' => false,
                    'label' => '<span type="button" class=" glyphicon glyphicon-remove-circle"></span>',
                    'options' => array('title' => 'Удалить', 'class' => 'text-center btn btn-danger'),
                    'url'=>'Yii::app()->createUrl("client/delete", array("id"=>$data->id))',
                ),

            ),
        ),
	),
)); ?>
    </div>
</div>

protected/views/client/create.php
<?php
/* @var $this ClientController */
/* @var $model Client */

$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'Управление клиентами', 'url'=>array('admin')),
);
?>
<div class="col-xs-12 block">
    <div class="col-xs-12 block_header">
        <h1>Создать клиента</h1>
    </div>
    <div class="col-xs-12 block_inner">
<?php $this->renderPartial('_form', array('model'=>$model)); ?>
        </div></div>

protected/views/client/index.php
<?php
/* @var $this ClientController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Clients',
);

$this->menu=array(
	array('label'=>'Create Client', 'url'=>array('create')),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>Clients</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>